using MyBox;
using UnityEngine;

public class MovableAddon : MonoBehaviour
{
    public bool Selected { get; private set;}
    [SerializeField] private LayerMask _hitLayers;
    [SerializeField] private LayerMask _hoverLayers;
    [SerializeField] private GameObject _rotationControls;
    [SerializeField] private GameObject _moveGizmo;

    private bool _dragging;
    [ReadOnly, SerializeField] private Vector3 _targetUp;
    [ReadOnly, SerializeField] private Vector3 _currentUp;
    private AddonsUIHelper _uiController;
    private MovableAddon _mirror;
    private HairPiece _controller;

    private Vector3 _loadedPos;
    private bool _isMirror;
    private Transform _nonMirror;

    public Transform Mirror => _mirror.transform;
    public void StoreLoadedPosition() => _loadedPos = transform.localPosition;
    public Vector3 TargetUp => _targetUp;
    public void SetTargetUp(Vector3 targetUp) => _targetUp = targetUp;
    public void SetAsMirror() => _isMirror = true;
    public void GiveNonMirror(Transform nonMirror) => _nonMirror = nonMirror;

    private void Start()
    {
        _uiController = FindObjectOfType<AddonsUIHelper>();
        _controller = GetComponentInParent<HairPiece>();
    }

    /// <summary>
    /// Returns a 12 digit string representing the rotation of the parent and then the child, parent rot first.
    /// </summary>
    public string GetRotString()
    {
        var parentRot = transform.localRotation;
        var childRot = transform.GetChild(0).localRotation;
        var returnString = Utils.EncodeQuaternions12(parentRot, childRot);
        //print("generated return quatString. rotA: " + parentRot + ", childRot: " + childRot + ", returnString: " + returnString);

        return returnString;
    }

    public void SetRot(string inputString)
    {
        //print("set rot string!");
        Utils.DecodeQuaternions12(inputString, out var parentRot, out var childRot);

        //print("decoded quatString. rotA: " + parentRot + ", childRot: " + childRot + ", inputString: " + inputString);

        transform.localRotation = parentRot;
        transform.GetChild(0).localRotation = childRot;

        _currentUp = transform.up;
        _targetUp = transform.localRotation * Vector3.up;

        if (_mirror) {

            _mirror.SetAsMirror();
            _mirror.GiveNonMirror(transform);   
            var surfaceNormal = transform.parent.TransformDirection(_targetUp);
            var mirrorUp = Vector3.Scale(transform.parent.InverseTransformDirection(surfaceNormal), new Vector3(-1, 1, 1));
            _mirror.SetTargetUp(Quaternion.AngleAxis(180f, mirrorUp) * mirrorUp);

            //print("Setting mirror targetUp: " + (Quaternion.AngleAxis(180f, mirrorUp) * mirrorUp));
        } 
    }

    /// <summary>
    /// Returns a 9 digit string for the local position of this object
    /// </summary>
    public string GetPosString()
    {
        string Format(float input)
        {
            int rounded = Mathf.RoundToInt((input + 5) * 100);
            int clamped = Mathf.Clamp(rounded, 0, 999);
            var result = clamped.ToString("D3");
            while (result.Length < 3) result = "0" + result;
            return result;
        }

        var pos = transform.localPosition;
        var x = Format(pos.x);
        var y = Format(pos.y);
        var z = Format(pos.z);
        var returnString = x + y + z;
        //print("generated pos string: " + returnString);

        return returnString;
    }

    /// <summary>
    /// Given a 9 digit string generated by 'GetPosString', sets the position of this object
    /// </summary>
    public void SetPos(string inputString)
    {
        float Decode(string input, int startingIndex)
        {
            var integer = int.Parse(input.Substring(startingIndex, 3));
            return integer / 100f - 5f;
        }

        float x = Decode(inputString, 0);
        float y = Decode(inputString, 3);
        float z = Decode(inputString, 6);

        //gameObject.name = Random.Range(0, 1000).ToString();
        //print(gameObject.name + ": decoded pos string. x: " + x + ", y: " + y + ", z: " + z + ", posString: " + inputString);
        transform.localPosition = new Vector3(x, y, z);
        _loadedPos = transform.localPosition;

        if (_mirror) {
            //print("mirror exists, setting its position");
            //_mirror.transform.localPosition = new Vector3(-x, y, z);

            Vector3 localPos = transform.parent.InverseTransformPoint(transform.position);
            localPos.x = -localPos.x;
            _mirror.transform.position = transform.parent.TransformPoint(localPos);
            _mirror.StoreLoadedPosition();
        }
    }

    public void SetSelected(bool selected)
    {
        if (transform.localPosition.magnitude < 0.1f) FixStartingPosition();

        Selected = selected;
    }

    private void FixStartingPosition()
    {
        bool didHit = Physics.Raycast(transform.position + Vector3.up * 5, Vector3.down, out var hitInfo, 1000, _hitLayers);
        if (!didHit) return;

        transform.position = hitInfo.point;
        _loadedPos = transform.localPosition;   
    }

    public void Initialize(MovableAddon mirror)
    {
        //print("initialize movable addon with mirror");
        _mirror = mirror;
    }

    private void OnDisable()
    {
        _rotationControls.SetActive(false);
        _moveGizmo.SetActive(false);
    }

    private void Update()
    {
        _currentUp = transform.up;

        if (_isMirror && _nonMirror) {
            transform.localEulerAngles = _nonMirror.localEulerAngles; 
            var child = transform.GetChild(0);
            var nonMirrorChild = _nonMirror.GetChild(0);
            child.localEulerAngles = nonMirrorChild.localEulerAngles;
            transform.parent.localScale = new Vector3(-1, 1, 1);
            transform.localPosition = _nonMirror.localPosition;
            return;
        }

        //Debug.DrawLine(transform.position, transform.position + transform.up * 10, Color.green);
        Quaternion targetLocalRot = Quaternion.FromToRotation(Vector3.up, _targetUp) * Quaternion.identity;
        transform.localRotation = Quaternion.Slerp(transform.localRotation, targetLocalRot, 20 * Time.deltaTime);

        if (_controller.IsMirroredVersion) {
            var scale = transform.localScale;
            scale.x = -Mathf.Abs(scale.x);
            transform.localScale = scale;
        }

        if (!GameManager.i || !_uiController.Addons) {
            if (_mirror) {
                transform.localPosition = _loadedPos;
            }

            _rotationControls.SetActive(false); 
            _moveGizmo.SetActive(false);
            return;
        }    

        _rotationControls.SetActive(_uiController.Rotating && Selected);
        _moveGizmo.SetActive(Selected && !_rotationControls.activeInHierarchy);
        if (!Selected) return;


        if (_uiController.Rotating) {
            _dragging = false;
            return;
        }

        if (!_dragging) {
            var didHover = Physics.Raycast(Camera.main.ScreenPointToRay(Input.mousePosition), out var hoverInfo, 1000, _hoverLayers);

            if (!didHover || hoverInfo.collider.GetComponentInParent<MovableAddon>() != this) return;

            if (Input.GetMouseButtonDown(0)) _dragging = true;
        }
        else {  

            if (Input.GetMouseButtonUp(0)) _dragging = false;

            var didHit = Physics.Raycast(Camera.main.ScreenPointToRay(Input.mousePosition), out var hitInfo, 1000, _hitLayers);
            if (!didHit) return;

            _targetUp = transform.parent.InverseTransformDirection(hitInfo.normal);
            transform.position = hitInfo.point;

            if (_mirror) {

                var mirrorUp = Vector3.Scale(transform.parent.InverseTransformDirection(hitInfo.normal), new Vector3(-1, 1, 1));
                _mirror._targetUp = Quaternion.AngleAxis(180f, mirrorUp) * mirrorUp;

                Vector3 localPos = transform.parent.InverseTransformPoint(hitInfo.point);
                localPos.x = -localPos.x;
                _mirror.transform.position = transform.parent.TransformPoint(localPos);
                _mirror.StoreLoadedPosition();
            }

            _loadedPos = transform.localPosition;   
        }
    }

}
