using MyBox;
using UnityEngine;

public class MovableAddon : MonoBehaviour
{
    public bool Selected { get; private set;}
    [SerializeField] private LayerMask _hitLayers;
    [SerializeField] private LayerMask _hoverLayers;
    [SerializeField] private GameObject _rotationControls;

    private bool _dragging;
    [ReadOnly, SerializeField] private Vector3 _targetUp;
    [ReadOnly, SerializeField] private Vector3 _currentUp;
    private AddonsUIHelper _uiController;
    private MovableAddon _mirror;
    private HairPiece _controller;

    public Transform Mirror => _mirror.transform;

    private void Start()
    {
        _uiController = FindObjectOfType<AddonsUIHelper>();
        _controller = GetComponentInParent<HairPiece>();
    }

    /// <summary>
    /// Returns a 12 digit string representing the rotation of the parent and then the child, parent rot first.
    /// </summary>
    public string GetRotString()
    {
        var parentRot = transform.localRotation;
        var childRot = transform.GetChild(0).localRotation;
        var returnString = Utils.EncodeQuaternions12(parentRot, childRot);
        //print("generated return quatString. rotA: " + parentRot + ", childRot: " + childRot + ", returnString: " + returnString);

        return returnString;
    }

    public void SetRot(string inputString)
    {
        Utils.DecodeQuaternions12(inputString, out var parentRot, out var childRot);

        //print("decoded quatString. rotA: " + parentRot + ", childRot: " + childRot + ", inputString: " + inputString);

        transform.localRotation = parentRot;
        transform.GetChild(0).localRotation = childRot;

        _currentUp = transform.up;
        _targetUp = transform.localRotation * Vector3.up;

        if (_mirror) {
            Vector3 mirrorUp = Vector3.Scale(_targetUp, new Vector3(-1f, 1f, 1f));
            _mirror._targetUp = Quaternion.AngleAxis(180f, mirrorUp) * mirrorUp;
        }
    }

    /// <summary>
    /// Returns a 9 digit string for the local position of this object
    /// </summary>
    public string GetPosString()
    {
        string Format(float input)
        {
            int rounded = Mathf.RoundToInt((input + 5) * 100);
            int clamped = Mathf.Clamp(rounded, 0, 999);
            var result = clamped.ToString("D3");
            while (result.Length < 3) result = "0" + result;
            return result;
        }

        var pos = transform.localPosition;
        var x = Format(pos.x);
        var y = Format(pos.y);
        var z = Format(pos.z);
        var returnString = x + y + z;
        //print("generated pos string: " + returnString);

        return returnString;
    }

    /// <summary>
    /// Given a 9 digit string generated by 'GetPosString', sets the position of this object
    /// </summary>
    public void SetPos(string inputString)
    {
        float Decode(string input, int startingIndex)
        {
            var integer = int.Parse(input.Substring(startingIndex, 3));
            return integer / 100f - 5f;
        }

        float x = Decode(inputString, 0);
        float y = Decode(inputString, 3);
        float z = Decode(inputString, 6);

        //print("decoded pos string. x: " + x + ", y: " + y + ", z: " + z + ", posString: " + inputString);
        transform.localPosition = new Vector3(x, y, z);

        /*Vector3 localPos = transform.parent.InverseTransformPoint(hitInfo.point);
        localPos.x = -localPos.x;
        _mirror.transform.position = transform.parent.TransformPoint(localPos);*/
    }

    public void SetSelected(bool selected)
    {
        Selected = selected;
    }

    public void Initialize(MovableAddon mirror)
    {
        _mirror = mirror; 
    }

    private void Update()
    {
        if (_controller.IsMirroredVersion) {
            var scale = transform.localScale;
            scale.x = -Mathf.Abs(scale.x);
            transform.localScale = scale;
        }

        _rotationControls.SetActive(_uiController.Rotating && Selected);
        if (!Selected) return;

        _currentUp = transform.up;
        Quaternion targetLocalRot = Quaternion.FromToRotation(Vector3.up, _targetUp) * Quaternion.identity;
        transform.localRotation = Quaternion.Slerp(transform.localRotation, targetLocalRot, 15 * Time.deltaTime);

        if (_uiController.Rotating) {
            _dragging = false;
            return;
        }

        if (!_dragging) {
            var didHover = Physics.Raycast(Camera.main.ScreenPointToRay(Input.mousePosition), out var hoverInfo, 1000, _hoverLayers);

            /*if (didHover) {
                print("collider: " + hoverInfo.collider.gameObject.name);
            }*/

            if (!didHover || hoverInfo.collider.GetComponentInParent<MovableAddon>() != this) return;

            if (Input.GetMouseButtonDown(0)) _dragging = true;
        }
        else {  

            if (Input.GetMouseButtonUp(0)) _dragging = false;

            var didHit = Physics.Raycast(Camera.main.ScreenPointToRay(Input.mousePosition), out var hitInfo, 1000, _hitLayers);
            if (!didHit) return;

            _targetUp = transform.parent.InverseTransformDirection(hitInfo.normal);
            transform.position = hitInfo.point;

            if (_mirror) {

                var mirrorUp = Vector3.Scale(transform.parent.InverseTransformDirection(hitInfo.normal), new Vector3(-1, 1, 1));
                _mirror._targetUp = Quaternion.AngleAxis(180f, mirrorUp) * mirrorUp;

                Vector3 localPos = transform.parent.InverseTransformPoint(hitInfo.point);
                localPos.x = -localPos.x;
                _mirror.transform.position = transform.parent.TransformPoint(localPos);
            }
        }
    }
}
